language:
  - python
  - cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6-dev
  - sudo apt-get install -qq wget

compiler:
  - gcc

python:
  - "2.7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5.3

# command to install dependencies
#install: "easy_install scons"

# command to run tests
#script: cd pipeline/build/ && . ../tools/init/bash && run scons --python_version 2.7.6

script: cd pipeline/build/ && scons -j 4
